baseURL = 'https://0xnakai.github.io/'
languageCode = 'en-us'

publishDir = "docs"


enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "America/Los_Angeles"
titlecasestyle = "Go"


[params.paige]
site_description = ""
site_title = "Taishi Nakai"


# サイトの選択肢を作る
[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.ja.menu.main]]
identifier = "home"
name = "ホーム"
url = "/ja"
weight = 10

[[languages.en.menu.main]]
identifier = "publication"
name = "Publication"
url = "/publication/"
weight = 20

[[languages.ja.menu.main]]
identifier = "publication"
name = "パブリケーション"
url = "/ja/publication/"
weight = 20

[[languages.en.menu.main]]
identifier = "post"
name = "Post"
url = "/post/"
weight = 40

[[languages.ja.menu.main]]
identifier = "post"
name = "ポスト"
url = "/ja/post/"
weight = 40

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "../themes/paige"

[outputs]
home = ["atom", "html", "paige-search", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]




